SELECT ((CAST(CURRENT_TIMESTAMP(0) AS DATE) - CAST(Start_ts AS DATE)) * 86400) 
            + ((EXTRACT(HOUR FROM CURRENT_TIMESTAMP(0)) - EXTRACT(HOUR FROM Start_ts)) * 3600)
            + ((EXTRACT(MINUTE FROM CURRENT_TIMESTAMP(0)) - EXTRACT(MINUTE FROM Start_ts)) * 60)
            + (EXTRACT(SECOND FROM CURRENT_TIMESTAMP(0)) - EXTRACT(SECOND FROM Start_ts))
FROM AnyTableWithAStart_tsColumn
